# Generated by Django 5.2.6 on 2025-09-09 18:00

import django.core.validators
import django.utils.timezone
import src.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=250, validators=[src.models.validate_not_empty, django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splitrule',
            name='effective_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.CharField(db_index=True, max_length=100, validators=[src.models.validate_not_empty, django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='splitrule',
            name='recipient_id',
            field=models.CharField(db_index=True, max_length=100, validators=[src.models.validate_not_empty, django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='splitrule',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, validators=[src.models.validate_not_empty]),
        ),
    ]
