# Generated by Django 5.2.6 on 2025-09-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
