# Generated by Django 5.2.6 on 2025-09-09 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitrule',
            name='effective_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
